### Before we begin, a (very) quick primer on AutoDiffXD:

In [1]:
from pydrake import math
import numpy as np

# pydrake.autodiffutils

Bindings for Eigen AutoDiff Scalars

### [Class]: pydrake.autodiffutils.AutoDiffXd

***_init__()*** and ***methods***:

In [2]:
#from pydrake.autodiffutils import AutoDiffXd
#from pydrake.autodiffutils import ExtractGradient

from pydrake import autodiffutils

# 1) Constructs a value with empty derivatives
#  value: float
a = autodiffutils.AutoDiffXd(1.5)

# 2) Constructs a value with the given derivatives.
#    value: float
#    derivatives: list of nth derivatives
a = autodiffutils.AutoDiffXd(1.5, [1.0, 0.0, 0.0])

# 3) value: float
#    offset: (int)
# Constructs a value with a single partial derivative of 1.0 
# at the given offset in a vector of size otherwise-zero derivatives.
a = autodiffutils.AutoDiffXd(1.5, 1, 0)

# ***pydrake.autodiffutils.AutoDiffXd methods:***
b = autodiffutils.AutoDiffXd(1.5, [1.0, 0.0, 0.0])

a.abs()
a.acos()
a.arccos()
a.arcsin()
a.arctan()
a.arctan2(b)     # Uses self for y in atan2(y, x).
a.asin()
a.atan()
a.atan2(b)       # Uses self for y in atan2(y, x).
a.ceil()
a.cos()
a.cosh()

derivs = a.derivatives()         # Return array of nth derivatives

a.exp()
a.floor()
a.log()
a.max(b)
a.min(b)
a.pow(2)
a.sin()
a.sinh()
a.sqrt()
a.tan()
a.tanh()

val = a.value()

print("a.value(): ", val)
print("a.derivatives(): ", derivs)

a.value():  1.5
a.derivatives():  [1.]


### [Function]: pydrake.autodiffutils.ExtractGradient

In [3]:
# Simple 1D example:
expra = math.sin(a)
autodiffutils.ExtractGradient(np.array([[expra]]))

array([[0.0707372]])

### [Function]: pydrake.autodiffutils.ExtractValue

Extracts the value() portion from a matrix of AutoDiffScalar entries. (Each entry contains a value and some derivatives.)

In [4]:
expra = math.sin(a)
exprb = math.cos(a)
exprc = math.tan(a)
exprd = math.sinh(a)

mat = np.array([[expra, exprb],
                [exprc, exprd]])

autodiffutils.ExtractValue(mat)

array([[ 0.99749499,  0.0707372 ],
       [14.10141995,  2.12927946]])

### [Function]: pydrake.autodiffutils.InitializeAutoDiff

Initializes a single AutoDiff matrix given the corresponding value matrix.

In [5]:
# Value matrix:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# gradient (as column vector where #rows = size(M))
grad = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1]]).T

M_ad = autodiffutils.InitializeAutoDiff(value=M, gradient=grad)
M_ad

array([[<AutoDiffXd 1.0 nderiv=1>, <AutoDiffXd 2.0 nderiv=1>,
        <AutoDiffXd 3.0 nderiv=1>],
       [<AutoDiffXd 4.0 nderiv=1>, <AutoDiffXd 5.0 nderiv=1>,
        <AutoDiffXd 6.0 nderiv=1>],
       [<AutoDiffXd 7.0 nderiv=1>, <AutoDiffXd 8.0 nderiv=1>,
        <AutoDiffXd 9.0 nderiv=1>]], dtype=object)

In [6]:
# Can be indexed into, like any ndarray:
M_ad[0]

array([<AutoDiffXd 1.0 nderiv=1>, <AutoDiffXd 2.0 nderiv=1>,
       <AutoDiffXd 3.0 nderiv=1>], dtype=object)

In [7]:
# You have to ask for the value of a cell
# you can't request the value of the whole matrix
# because it is an ndarray:
M_ad[0][0].value()

1.0

In [8]:
# Or... you can ExtractValues INTO an ndarray:
autodiffutils.ExtractValue(M_ad)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### [Function]: pydrake.autodiffutils.InitializeAutoDiffTuple

Given a series of array_like input arguments, create a tuple of corresponding AutoDiff matrices with values equal to the input matrices and properly initialized derivative vectors.

In [9]:
# This gives you properly initialized derivatives in one function call:

# Value matrix:
vals = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

tup = autodiffutils.InitializeAutoDiffTuple(vals)

In [10]:
tup[0][0][0].value()

1.0

In [11]:
# The size of the derivative vector of each element 
# of the matrices/arrays in the output tuple will 
# be the same, and will equal the sum of the number 
# of elements of the matrices in args.
tup[0][0][0].derivatives()

array([1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# Extract by index0
autodiffutils.ExtractValue(tup[0])

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])